# Site settings
title: PyCon Namibia
email: vincent.knight@gmail.com
description: Five days of talks, workshops and collaboration in Windhoek, Namibia
baseurl: ""
url: "https://python-namibia.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygmentzs
