# Site settings
title: Un peu de math
email: vincent.knight@gmail.com
description: "I post stuff here about game theory, queueing theory, pedagogy, Sage, Python and other things..."
baseurl: "/python-namibia.github.io"
url: "https://python-namibia.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
